### ISSUE TITLE
Numerical (section) file extensions not supported

### ISSUE THREAD

**Issue by alexrp** [bartosz-antosik/vscode-troff#1]
In many projects, `man` pages are stored with a file extension matching its section, even in the source tree. For example, in Mono: https://github.com/mono/mono/tree/master/man

It's also worth noting that the TextMate language definition this is based on lists these: https://github.com/bartosz-antosik/vscode-troff/blob/master/syntaxes/troff.tmLanguage#L7

This extension should probably support these as well, here: https://github.com/bartosz-antosik/vscode-troff/blob/master/package.json#L27

**Comment by bartosz-antosik** [comment]
Hi! Wow! First issue! Thanks for the tip! I will have a look into this, could be worth extending.

**Comment by mikemol** [comment]
@bartosz-antosik, yes, please. And a preview window (i.e. markdown preview, but for troff) would be fantastic.
